# Generated by Django 2.0.2 on 2018-02-04 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webtoon', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='title',
            new_name='episode_title',
        ),
    ]
