# Generated by Django 2.0.2 on 2018-02-04 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtoon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webtoon',
            name='webtoon_id',
            field=models.CharField(blank=True, default='webtoon id', max_length=200, null=True),
        ),
    ]
