# Generated by Django 2.0.2 on 2018-02-04 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webtoon', '0002_auto_20180204_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='webtoon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webtoon.Webtoon'),
        ),
        migrations.AlterField(
            model_name='webtoon',
            name='webtoon_id',
            field=models.CharField(default='webtoon id', max_length=200),
        ),
    ]
